FIND_PACKAGE(libmongocxx)

IF(libmongocxx_FOUND)
    ADD_LIBRARY(mongo::mongocxx INTERFACE IMPORTED)
    SET_TARGET_PROPERTIES(mongo::mongocxx PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${LIBMONGOCXX_INCLUDE_DIRS}"
            INTERFACE_LINK_LIBRARIES "${LIBMONGOCXX_LIBRARIES}")
ENDIF()